apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: server
build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: agex
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: theta-computing-366519
deploy:
  kubectl:
    manifests:
    - k8s-agones/*.yml
